benchmark: TW:0050
date_mode: intersection
return_type: total_return
risk_free_rate: 0.0
drive_output_root: /content/drive/MyDrive/00Quant_Research/compare_stock_return
use_cache: true
refresh_cache: false
strict: false
custom_start_date: null
custom_end_date: null
display_symbols: null
fees: {}
custom_assets: {}
holdings_files: {}
assets:
- TW:0050
- TW:009816
- TW:0056
- US:VOO
- US:VGT
fx_mode: none
portfolios:
  TW 0050 only:
    TW:0050: 1.0
  0050 + VOO:
    TW:0050: 0.33
    US:VOO: 0.67
  0050 + VOO + VGT:
    TW:0050: 0.3
    US:VOO: 0.5
    US:VGT: 0.2
  009816 + VOO + VGT:
    TW:009816: 0.3
    US:VOO: 0.5
    US:VGT: 0.2
